package com.shovinus.chopdownupdated.config;

/**
 * All built in tree config data of the supported mods. The data is written to
 * config/chopdownupdated/<modid>.json on first use and can then be edited by
 * players.
 */
public final class BuiltinTreeConfigs {

	private BuiltinTreeConfigs() {
	}

	public static final TreeConfigData[] ALL = {
			TreeConfigData.of("AbyssalCraft", "abyssalcraft",
					new TreeConfiguration().setLogs("abyssalcraft:dreadlog:0", "abyssalcraft:dreadlog:12").setLeaves("abyssalcraft:dreadleaves:.*"),
					new TreeConfiguration().setLogs("abyssalcraft:dltlog:0", "abyssalcraft:dltlog:12").setLeaves("abyssalcraft:dltleaves:.*")),
			TreeConfigData.of("AetherLegacy", "aether_legacy",
					new TreeConfiguration().setLogs("aether_legacy:aether_log:.*").setLeaves("aether_legacy:aether_leaves:.*", "aether_legacy:crystal_leaves:.*", "aether_legacy:holiday_leaves:.*")),
			TreeConfigData.of("BetterWithAddons", "betterwithaddons",
					new TreeConfiguration().setLogs("betterwithaddons:log_mulberry:0").setLeaves("betterwithaddons:leaves_mulberry:.*"),
					new TreeConfiguration().setLogs("betterwithaddons:log_sakura:0").setLeaves("betterwithaddons:leaves_sakura:.*"),
					new TreeConfiguration().setLogs("betterwithaddons:log_luretree:0", "betterwithaddons:log_luretree_face:0").setLeaves("betterwithaddons:leaves_luretree:.*")),
			TreeConfigData.of("BiomesOPlenty", "biomesoplenty",
					new TreeConfiguration(16,12,0,3).setLogs("biomesoplenty:log_0:4").setLeaves("biomesoplenty:leaves_3:.*").setMinCutRatio(0.6),
					new TreeConfiguration().setLogs("biomesoplenty:log_0:5").setLeaves("biomesoplenty:leaves_2:.*"),
					new TreeConfiguration().setLogs("biomesoplenty:log_0:6").setLeaves("biomesoplenty:leaves_1:.*", "biomesoplenty:leaves_0:.*"),
					new TreeConfiguration().setLogs("biomesoplenty:log_0:7").setLeaves("biomesoplenty:leaves_1:.*"),
					new TreeConfiguration().setLogs("biomesoplenty:log_1:4").setLeaves("biomesoplenty:leaves_0:.*"),
					new TreeConfiguration().setLogs("biomesoplenty:log_1:5").setLeaves("biomesoplenty:leaves_0:.*"),
					new TreeConfiguration(9,12,0,3).setLogs("biomesoplenty:log_1:6").setLeaves("biomesoplenty:leaves_4:.*").setMinCutRatio(0.6),
					new TreeConfiguration().setLogs("biomesoplenty:log_1:7").setLeaves("biomesoplenty:leaves_4:.*"),
					new TreeConfiguration(9,12,0,5).setLogs("biomesoplenty:log_2:4").setLeaves("biomesoplenty:leaves_4:.*").setMinCutRatio(0.6),
					new TreeConfiguration(9,12,4,1).setLogs("biomesoplenty:log_2:5").setLeaves("biomesoplenty:leaves_4:.*"),
					new TreeConfiguration().setLogs("biomesoplenty:log_2:6").setLeaves("biomesoplenty:leaves_5:.*"),
					new TreeConfiguration().setLogs("biomesoplenty:log_2:7").setLeaves("biomesoplenty:leaves_3:.*"),
					new TreeConfiguration().setLogs("biomesoplenty:log_3:4").setLeaves("biomesoplenty:leaves_3:.*"),
					new TreeConfiguration().setLogs("biomesoplenty:log_3:5").setLeaves("biomesoplenty:leaves_5:.*"),
					new TreeConfiguration().setLogs("biomesoplenty:log_3:6").setLeaves("biomesoplenty:leaves_5:.*"),
					new TreeConfiguration().setLogs("biomesoplenty:log_3:7").setLeaves("biomesoplenty:leaves_5:.*"),
					new TreeConfiguration().setLogs("minecraft:log:0").setLeaves("biomesoplenty:leaves_0:.*", "biomesoplenty:leaves_3:.*", "biomesoplenty:leaves_2:.*", "biomesoplenty:leaves_1:.*"),
					new TreeConfiguration().setLogs("minecraft:log:2").setLeaves("biomesoplenty:leaves_0:.*"),
					new TreeConfiguration().setLogs("minecraft:log2:0").setLeaves("biomesoplenty:leaves_0:.*"),
					new TreeConfiguration().setLogs("minecraft:log2:1").setLeaves("biomesoplenty:leaves_0:.*", "biomesoplenty:leaves_1:.*")),
			TreeConfigData.of("Cuisine", "cuisine",
					new TreeConfiguration().setLogs("cuisine:log:0").setLeaves("cuisine:sheared_leaves:.*")),
			TreeConfigData.of("DefiledLands", "defiledlands",
					new TreeConfiguration().setLogs("defiledlands:tenebra_log:0").setLeaves("defiledlands:tenebra_leaves:.*")),
			TreeConfigData.of("ExtraTrees", "extratrees",
					new TreeConfiguration().setLogs("extratrees:logs:0").setLeaves()),
			TreeConfigData.of("Forestry", "forestry",
					new TreeConfiguration().setLogs("forestry:logs.0:0").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.0:1").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.0:2").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.0:3").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.1:0").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.1:1").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.1:2").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration(14,12,0,3).setLogs("forestry:logs.1:3").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*").setMinCutRatio(0.6),
					new TreeConfiguration().setLogs("forestry:logs.2:0").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.2:1").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.2:2").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.2:3").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.3:0").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.3:1").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.3:2").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.3:3").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.4:0").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.4:1").setLeaves("forestry:leaves.default.2:.*", "forestry:leaves.decorative.2:.*"),
					new TreeConfiguration().setLogs("forestry:logs.4:2").setLeaves("forestry:leaves.default.2:.*", "forestry:leaves.decorative.2:.*"),
					new TreeConfiguration().setLogs("forestry:logs.4:3").setLeaves("forestry:leaves.default.2:.*", "forestry:leaves.decorative.2:.*"),
					new TreeConfiguration().setLogs("forestry:logs.5:0").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.5:1").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.5:2").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.5:3").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration(16,12,0,4).setLogs("forestry:logs.6:0").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*").setMinCutRatio(0.6),
					new TreeConfiguration().setLogs("forestry:logs.6:1").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.6:2").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.6:3").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.7:0").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.0:0").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.0:1").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.0:2").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.0:3").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.1:0").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.1:1").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.1:2").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration(14,12,0,3).setLogs("forestry:logs.fireproof.1:3").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*").setMinCutRatio(0.6),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.2:0").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.2:1").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.2:2").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.2:3").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.3:0").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.3:1").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.3:2").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.3:3").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.4:0").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.4:1").setLeaves("forestry:leaves.default.2:.*", "forestry:leaves.decorative.2:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.4:2").setLeaves("forestry:leaves.default.2:.*", "forestry:leaves.decorative.2:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.4:3").setLeaves("forestry:leaves.default.2:.*", "forestry:leaves.decorative.2:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.5:0").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.5:1").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.5:2").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.5:3").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration(16,12,0,4).setLogs("forestry:logs.fireproof.6:0").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*").setMinCutRatio(0.6),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.6:1").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.6:2").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.6:3").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.fireproof.7:0").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.vanilla.fireproof.0:0").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.vanilla.fireproof.0:1").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.vanilla.fireproof.0:2").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.vanilla.fireproof.0:3").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("forestry:logs.vanilla.fireproof.1:0").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("forestry:logs.vanilla.fireproof.1:1").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("minecraft:log:0").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("minecraft:log:1").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("minecraft:log:2").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("minecraft:log:3").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*"),
					new TreeConfiguration().setLogs("minecraft:log2:0").setLeaves("forestry:leaves.default.1:.*", "forestry:leaves.decorative.1:.*"),
					new TreeConfiguration().setLogs("minecraft:log2:1").setLeaves("forestry:leaves.default.0:.*", "forestry:leaves.decorative.0:.*")),
			TreeConfigData.of("IndustrialCraft2", "ic2",
					new TreeConfiguration().setLogs("ic2:rubber_wood:0").setLeaves("ic2:leaves:.*")),
			TreeConfigData.of("IntegratedDynamics", "integrateddynamics",
					new TreeConfiguration().setLogs("integrateddynamics:menril_log:0", "integrateddynamics:menril_log_filled:0").setLeaves("integrateddynamics:menril_leaves:.*"),
					new TreeConfiguration().setLogs("integrateddynamics:menrilLog:0", "integrateddynamics:menrilFilledLog:0").setLeaves("integrateddynamics:menrilLeaves:.*")),
			TreeConfigData.of("JurassiCraft", "jurassicraft",
					new TreeConfiguration().setLogs("jurassicraft:araucaria_log:0").setLeaves("jurassicraft:araucaria_leaves:.*"),
					new TreeConfiguration().setLogs("jurassicraft:psaronius_log:0").setLeaves("jurassicraft:psaronius_leaves:.*"),
					new TreeConfiguration().setLogs("jurassicraft:calamites_log:0").setLeaves("jurassicraft:calamites_leaves:.*"),
					new TreeConfiguration().setLogs("jurassicraft:phoenix_log:0").setLeaves("jurassicraft:phoenix_leaves:.*"),
					new TreeConfiguration().setLogs("jurassicraft:ginkgo_log:0").setLeaves("jurassicraft:ginkgo_leaves:.*")),
			TreeConfigData.of("Natura", "natura",
					new TreeConfiguration().setLogs("natura:nether_logs:0").setLeaves("natura:nether_leaves:.*"),
					new TreeConfiguration().setLogs("natura:nether_logs:1").setLeaves("natura:nether_leaves2:.*"),
					new TreeConfiguration().setLogs("natura:nether_logs:2").setLeaves("natura:nether_leaves:.*"),
					new TreeConfiguration().setLogs("natura:nether_logs2:0").setLeaves("natura:nether_leaves:.*").setHanging(true),
					new TreeConfiguration().setLogs("natura:apple_log:.*").setLeaves("natura:apple_leaves:.*"),
					new TreeConfiguration().setLogs("natura:overworld_logs:0").setLeaves("natura:overworld_leaves:.*"),
					new TreeConfiguration().setLogs("natura:overworld_logs:1").setLeaves("natura:overworld_leaves:.*"),
					new TreeConfiguration().setLogs("natura:overworld_logs:2").setLeaves("natura:overworld_leaves:.*"),
					new TreeConfiguration().setLogs("natura:overworld_logs:3").setLeaves("natura:overworld_leaves:.*"),
					new TreeConfiguration().setLogs("natura:overworld_logs2:0").setLeaves("natura:overworld_leaves2:.*"),
					new TreeConfiguration().setLogs("natura:overworld_logs2:1").setLeaves("natura:overworld_leaves2:.*"),
					new TreeConfiguration().setLogs("natura:overworld_logs2:2").setLeaves("natura:overworld_leaves2:.*"),
					new TreeConfiguration().setLogs("natura:overworld_logs2:3").setLeaves("natura:overworld_leaves2:.*"),
					new TreeConfiguration(32, 48, 20, 8).setLogs("natura:redwood_logs:0", "natura:redwood_logs:1", "natura:redwood_logs:2").setLeaves("natura:redwood_leaves:.*").setMinCutRatio(0.6)),
			TreeConfigData.of("NaturalPledge", "naturalpledge",
					new TreeConfiguration().setLogs("naturalpledge:iris_log0:0").setLeaves("naturalpledge:iris_leaves0:.*"),
					new TreeConfiguration().setLogs("naturalpledge:iris_log0:1").setLeaves("naturalpledge:iris_leaves0:.*"),
					new TreeConfiguration().setLogs("naturalpledge:iris_log0:2").setLeaves("naturalpledge:iris_leaves0:.*"),
					new TreeConfiguration().setLogs("naturalpledge:iris_log0:3").setLeaves("naturalpledge:iris_leaves0:.*"),
					new TreeConfiguration().setLogs("naturalpledge:iris_log1:0").setLeaves("naturalpledge:iris_leaves1:.*"),
					new TreeConfiguration().setLogs("naturalpledge:iris_log1:1").setLeaves("naturalpledge:iris_leaves1:.*"),
					new TreeConfiguration().setLogs("naturalpledge:iris_log1:2").setLeaves("naturalpledge:iris_leaves1:.*"),
					new TreeConfiguration().setLogs("naturalpledge:iris_log1:3").setLeaves("naturalpledge:iris_leaves1:.*"),
					new TreeConfiguration().setLogs("naturalpledge:iris_log2:0").setLeaves("naturalpledge:iris_leaves2:.*"),
					new TreeConfiguration().setLogs("naturalpledge:iris_log2:1").setLeaves("naturalpledge:iris_leaves2:.*"),
					new TreeConfiguration().setLogs("naturalpledge:iris_log2:2").setLeaves("naturalpledge:iris_leaves2:.*"),
					new TreeConfiguration().setLogs("naturalpledge:iris_log2:3").setLeaves("naturalpledge:iris_leaves2:.*"),
					new TreeConfiguration().setLogs("naturalpledge:iris_log3:0").setLeaves("naturalpledge:iris_leaves3:.*"),
					new TreeConfiguration().setLogs("naturalpledge:iris_log3:1").setLeaves("naturalpledge:iris_leaves3:.*"),
					new TreeConfiguration().setLogs("naturalpledge:iris_log3:2").setLeaves("naturalpledge:iris_leaves3:.*"),
					new TreeConfiguration().setLogs("naturalpledge:iris_log3:3").setLeaves("naturalpledge:iris_leaves3:.*"),
					new TreeConfiguration().setLogs("naturalpledge:alt_log0:0").setLeaves("naturalpledge:alt_leaves0:.*"),
					new TreeConfiguration().setLogs("naturalpledge:alt_log0:1").setLeaves("naturalpledge:alt_leaves0:.*"),
					new TreeConfiguration().setLogs("naturalpledge:alt_log0:2").setLeaves("naturalpledge:alt_leaves0:.*"),
					new TreeConfiguration().setLogs("naturalpledge:alt_log0:3").setLeaves("naturalpledge:alt_leaves0:.*"),
					new TreeConfiguration().setLogs("naturalpledge:alt_log1:0").setLeaves("naturalpledge:alt_leaves1:.*"),
					new TreeConfiguration().setLogs("naturalpledge:alt_log1:1").setLeaves("naturalpledge:alt_leaves1:.*"),
					new TreeConfiguration().setLogs("naturalpledge:rainbow_log:0").setLeaves("naturalpledge:rainbow_leaves:.*"),
					new TreeConfiguration().setLogs("naturalpledge:aurora_log:0").setLeaves("naturalpledge:aurora_leaves:.*"),
					new TreeConfiguration().setLogs("naturalpledge:thunder_log:0").setLeaves("naturalpledge:thunder_leaves:.*"),
					new TreeConfiguration().setLogs("naturalpledge:seal_log:0").setLeaves("naturalpledge:seal_leaves:.*"),
					new TreeConfiguration().setLogs("naturalpledge:circuit_log:0").setLeaves("naturalpledge:circuit_leaves:.*"),
					new TreeConfiguration().setLogs("naturalpledge:calico_log:0").setLeaves("naturalpledge:calico_leaves:.*")),
			TreeConfigData.of("PamsHarvestCraft", "harvestcraft",
					new TreeConfiguration().setLogs("harvestcraft:pamcinnamon:0").setLeaves("minecraft:leaves:.*"),
					new TreeConfiguration().setLogs("harvestcraft:pammaple:0").setLeaves("minecraft:leaves:.*"),
					new TreeConfiguration().setLogs("minecraft:log:3", "harvestcraft:pampaperbark:0").setLeaves()),
			TreeConfigData.of("Plants", "plants2",
					new TreeConfiguration().setLogs("plants2:crystal_log:0").setLeaves("plants2:crystal_leaves:.*"),
					new TreeConfiguration().setLogs("plants2:crystal_log:1").setLeaves("plants2:crystal_leaves:.*"),
					new TreeConfiguration().setLogs("plants2:log_0:0").setLeaves("plants2:leaves_0:.*"),
					new TreeConfiguration().setLogs("plants2:log_0:1").setLeaves("plants2:leaves_0:.*"),
					new TreeConfiguration().setLogs("plants2:log_0:2").setLeaves("plants2:leaves_0:.*"),
					new TreeConfiguration().setLogs("plants2:log_0:3").setLeaves("plants2:leaves_0:.*"),
					new TreeConfiguration().setLogs("plants2:nether_log:1").setLeaves("plants2:nether_leaves:.*"),
					new TreeConfiguration().setLogs("plants2:nether_log:0").setLeaves("plants2:nether_leaves:.*")),
			TreeConfigData.of("PrimalCore", "primal",
					new TreeConfiguration().setLogs("primal:logs:0").setLeaves("primal:leaves:.*"),
					new TreeConfiguration().setLogs("primal:logs:1").setLeaves("primal:leaves:.*")),
			TreeConfigData.of("Rustic", "rustic",
					new TreeConfiguration().setLogs("rustic:log:0").setLeaves("rustic:leaves:.*"),
					new TreeConfiguration().setLogs("rustic:log:1").setLeaves("rustic:leaves:.*")),
			TreeConfigData.of("SugiForest", "sugiforest",
					new TreeConfiguration().setLogs("sugiforest:sugi_log:0").setLeaves("sugiforest:sugi_leaves:.*")),
			TreeConfigData.of("Terra", "terra",
					new TreeConfiguration().setLogs("terra:blackspruce_log:0").setLeaves("terra:blackspruce_leaves:.*"),
					new TreeConfiguration().setLogs("terra:bluespruce_log:0").setLeaves("terra:bluespruce_leaves:.*"),
					new TreeConfiguration().setLogs("terra:cherry_log:0").setLeaves("terra:cherry_leaves_white:.*", "terra:cherry_leaves_purple:.*"),
					new TreeConfiguration().setLogs("terra:ebony_log:0").setLeaves("terra:palm_leaves:.*"),
					new TreeConfiguration().setLogs("terra:elm_log:0").setLeaves("terra:elm_leaves:.*"),
					new TreeConfiguration().setLogs("terra:jacaranda_log:0").setLeaves("terra:jacaranda_leaves_magenta:.*", "terra:jacaranda_leaves_green:.*"),
					new TreeConfiguration().setLogs("terra:mahogany_log:0").setLeaves("terra:mahogany_leaves:.*"),
					new TreeConfiguration().setLogs("terra:palm_log:0").setLeaves("terra:palm_leaves:.*"),
					new TreeConfiguration().setLogs("terra:paulownia_log:0").setLeaves("terra:paulownia_leaves_green:.*", "terra:paulownia_leaves_white:.*", "terra:paulownia_leaves_blue:.*"),
					new TreeConfiguration().setLogs("terra:redspruce_log:0").setLeaves("terra:redspruce_leaves:.*"),
					new TreeConfiguration().setLogs("terra:whitespruce_log:0").setLeaves("terra:whitespruce_leaves:.*")),
			TreeConfigData.of("Terraqueous", "terraqueous",
					new TreeConfiguration().setLogs("terraqueous:trunk1:0").setLeaves("terraqueous:foliage1:.*"),
					new TreeConfiguration().setLogs("terraqueous:trunk1:1").setLeaves("terraqueous:foliage1:.*"),
					new TreeConfiguration().setLogs("terraqueous:trunk1:2").setLeaves("terraqueous:foliage2:.*"),
					new TreeConfiguration().setLogs("terraqueous:trunk1:3").setLeaves("terraqueous:foliage2:.*"),
					new TreeConfiguration().setLogs("terraqueous:trunk1:4").setLeaves("terraqueous:foliage3:.*"),
					new TreeConfiguration().setLogs("terraqueous:trunk2:0").setLeaves("terraqueous:foliage3:.*"),
					new TreeConfiguration().setLogs("terraqueous:trunk2:1").setLeaves("terraqueous:foliage4:.*"),
					new TreeConfiguration().setLogs("terraqueous:trunk2:2").setLeaves("terraqueous:foliage4:.*"),
					new TreeConfiguration().setLogs("terraqueous:trunk2:3").setLeaves("terraqueous:foliage5:.*"),
					new TreeConfiguration().setLogs("terraqueous:trunk2:4").setLeaves("terraqueous:foliage5:.*")),
			TreeConfigData.of("Thaumcraft", "thaumcraft",
					new TreeConfiguration(15,15,0,0).setLogs("thaumcraft:log_greatwood:0").setLeaves("thaumcraft:leaves_greatwood:.*"),
					new TreeConfiguration(15,15,0,0).setLogs("thaumcraft:log_silverwood:0").setLeaves("thaumcraft:leaves_silverwood:.*")),
			TreeConfigData.of("TheBetweenLands", "thebetweenlands",
					new TreeConfiguration(32,20,15,5).setLogs("thebetweenlands:log_weedwood:.*", "thebetweenlands:weedwood:.*", "thebetweenlands:log_rotten_bark:0", "thebetweenlands:dentrothyst:0").setLeaves("thebetweenlands:leaves_weedwood_tree:.*", "thebetweenlands:shelf_fungus:.*").setMinCutRatio(0.6),
					new TreeConfiguration().setLogs("thebetweenlands:log_sap:0").setLeaves("thebetweenlands:leaves_sap_tree:.*"),
					new TreeConfiguration().setLogs("thebetweenlands:log_nibbletwig:.*").setLeaves("thebetweenlands:leaves_nibbletwig_tree:.*"),
					new TreeConfiguration().setLogs("thebetweenlands:log_rubber:.*").setLeaves("thebetweenlands:leaves_rubber_tree:.*"),
					new TreeConfiguration(9,12,5,3).setLogs("thebetweenlands:log_hearthgrove:.*").setLeaves("thebetweenlands:leaves_hearthgrove_tree:.*").setMinCutRatio(0.6),
					new TreeConfiguration().setLogs("thebetweenlands:bulb_capped_mushroom_stalk:.*").setLeaves("thebetweenlands:bulb_capped_mushroom_cap:.*"),
					new TreeConfiguration().setLogs("thebetweenlands:log_spirit_tree:.*").setLeaves("thebetweenlands:leaves_spirit_tree_top:.*", "thebetweenlands:leaves_spirit_tree_middle:.*", "thebetweenlands:leaves_spirit_tree_bottom:.*")),
			TreeConfigData.of("TheErebus", "erebus",
					new TreeConfiguration().setLogs("erebus:log_baobab:0").setLeaves("erebus:leaves_baobab:.*"),
					new TreeConfiguration().setLogs("erebus:log_eucalyptus:0").setLeaves("erebus:leaves_eucalyptus:.*"),
					new TreeConfiguration().setLogs("erebus:log_mahogany:0").setLeaves("erebus:leaves_mahogany:.*"),
					new TreeConfiguration().setLogs("erebus:log_mossbark:0").setLeaves("erebus:leaves_mossbark:.*"),
					new TreeConfiguration().setLogs("erebus:log_asper:0").setLeaves("erebus:leaves_asper:.*"),
					new TreeConfiguration().setLogs("erebus:log_cypress:0").setLeaves("erebus:leaves_cypress:.*"),
					new TreeConfiguration().setLogs("erebus:log_marshwood:0").setLeaves("erebus:leaves_marshwood:.*"),
					new TreeConfiguration().setLogs("erebus:log_balsam:0").setLeaves("erebus:leaves_balsam:.*")),
			TreeConfigData.of("TheMidnight", "midnight",
					new TreeConfiguration().setLogs("midnight:dark_willow_log:0").setLeaves("midnight:dark_willow_leaves:.*"),
					new TreeConfiguration().setLogs("midnight:shadowroot_log:0").setLeaves("midnight:shadowroot_leaves:.*")),
			TreeConfigData.of("TheTwilightForest", "twilightforest",
					new TreeConfiguration(20,12,0,1).setLogs("twilightforest:twilight_log:0").setLeaves("twilightforest:twilight_leaves:.*"),
					new TreeConfiguration().setLogs("twilightforest:twilight_log:1").setLeaves("twilightforest:twilight_leaves:.*"),
					new TreeConfiguration(9,12,4,5).setLogs("twilightforest:twilight_log:2").setLeaves("twilightforest:twilight_leaves:.*", "twilightforest:magic_leaves:.*").setMinCutRatio(0.6),
					new TreeConfiguration().setLogs("twilightforest:twilight_log:3").setLeaves("twilightforest:dark_leaves:.*"),
					new TreeConfiguration().setLogs("twilightforest:magic_log:0", "twilightforest:magic_log_core:0").setLeaves("twilightforest:magic_leaves:.*"),
					new TreeConfiguration().setLogs("twilightforest:magic_log:1", "twilightforest:magic_log_core:1").setLeaves("twilightforest:magic_leaves:.*"),
					new TreeConfiguration().setLogs("twilightforest:magic_log:2", "twilightforest:magic_log_core:2").setLeaves("twilightforest:magic_leaves:.*"),
					new TreeConfiguration().setLogs("twilightforest:magic_log:3", "twilightforest:magic_log_core:3").setLeaves("twilightforest:magic_leaves:.*")),
			TreeConfigData.of("Traverse", "traverse",
					new TreeConfiguration().setLogs("traverse:fir_log:0").setLeaves("traverse:fir_leaves:.*"),
					new TreeConfiguration().setLogs("minecraft:log:0").setLeaves("traverse:red_autumnal_leaves:.*", "traverse:brown_autumnal_leaves:.*", "traverse:yellow_autumnal_leaves:.*")),
			TreeConfigData.of("Treasure2", "treasure2",
					new TreeConfiguration().setLogs("treasure2:wither_log:0", "treasure2:wither_log_soul:0", "treasure2:wither_broken_log:0").setLeaves()),
			TreeConfigData.of("Tropicraft", "tropicraft",
					new TreeConfiguration(15,14,0,0).setLogs("tropicraft:log:0").setLeaves("tropicraft:leaves:.*"),
					new TreeConfiguration().setLogs("tropicraft:log:1").setLeaves("tropicraft:leaves:.*"),
					new TreeConfiguration().setLogs("minecraft:log:0").setLeaves("tropicraft:leaves:.*", "tropicraft:leaves_fruit:.*")),
			TreeConfigData.of("Vanilla", "minecraft",
					new TreeConfiguration().setLogs("minecraft:log:0").setLeaves("minecraft:leaves:.*"),
					new TreeConfiguration().setLogs("minecraft:log:1").setLeaves("minecraft:leaves:.*"),
					new TreeConfiguration().setLogs("minecraft:log:2").setLeaves("minecraft:leaves:.*"),
					new TreeConfiguration().setLogs("minecraft:log:3").setLeaves("minecraft:leaves:.*"),
					new TreeConfiguration().setLogs("minecraft:log2:0").setLeaves("minecraft:leaves2:.*"),
					new TreeConfiguration().setLogs("minecraft:log2:1").setLeaves("minecraft:leaves2:.*"),
					new TreeConfiguration().setLogs("minecraft:brown_mushroom:0").setLeaves(),
					new TreeConfiguration().setLogs("minecraft:red_mushroom:0").setLeaves()),
			TreeConfigData.of("VibrantJourneys", "pvj",
					new TreeConfiguration().setLogs("pvj:log_willow:0").setLeaves("pvj:leaves_willow:.*"),
					new TreeConfiguration().setLogs("pvj:log_mangrove:0").setLeaves("pvj:leaves_mangrove:.*"),
					new TreeConfiguration().setLogs("pvj:log_palm:0").setLeaves("pvj:leaves_palm:.*"),
					new TreeConfiguration().setLogs("pvj:log_redwood:0").setLeaves("pvj:leaves_redwood:.*"),
					new TreeConfiguration().setLogs("pvj:log_fir:0").setLeaves("pvj:leaves_fir:.*"),
					new TreeConfiguration().setLogs("pvj:log_pine:0").setLeaves("pvj:leaves_pine:.*"),
					new TreeConfiguration().setLogs("pvj:log_aspen:0").setLeaves("pvj:leaves_aspen:.*"),
					new TreeConfiguration().setLogs("pvj:log_maple:0").setLeaves("pvj:leaves_red_maple:.*", "pvj:leaves_orange_maple:.*"),
					new TreeConfiguration().setLogs("pvj:log_baobab:0").setLeaves("pvj:leaves_baobab:.*"),
					new TreeConfiguration().setLogs("pvj:log_cottonwood:0").setLeaves("pvj:leaves_cottonwood:.*"))
	};
}
